### ISSUE TITLE
README mentions testing custom enumerators via #build_enumerator but should that be #enumerator_builder?

### ISSUE THREAD

**Issue by yjukaku** [Shopify/maintenance_tasks#1049]
Hello, thanks for your work on this project. We're finding it very helpful.

I had to write a task that uses a custom enumerator, and I followed the steps in the README here: https://github.com/Shopify/maintenance_tasks?tab=readme-ov-file#tasks-with-custom-enumerators

> If you have a special use case requiring iteration over an unsupported collection type, such as external resources fetched from some API, you can implement the enumerator_builder(cursor:) method in your task.

Which I've done. [Later in the README](https://github.com/Shopify/maintenance_tasks?tab=readme-ov-file#writing-tests-for-a-task-that-uses-a-custom-enumerator), though, under "Writing tests for a Task that uses a custom enumerator":

> Tests for tasks that use custom enumerators need to instantiate the task class in order to call #build_enumerator. Once the task instance is set up, validate that #build_enumerator returns an enumerator yielding pairs of [item, cursor] as expected.

Is this correct? When I try to instantiate a task and call #build_enumerator, I get a NoMethodError. Looking through the source, it looks like [build_enumerator is defined on a different class](https://github.com/Shopify/maintenance_tasks/blob/b93a378e321c21dadbf0dcbb6e79648d33ed3182/app/jobs/concerns/maintenance_tasks/task_job_concern.rb#L33) (Maintenance::TaskJob), not on `Maintenance::Task`. Or am I missing something?

**Comment by adrianna-chang-shopify** [comment]
Hi @yjukaku , thanks for the issue!

> Tests for tasks that use custom enumerators need to instantiate the task class in order to call #build_enumerator. 

This doesn't look right to me 🤦‍♀️ Tasks should use the `enumerator_builder` method first described in the documentation for defining custom enums. `#build_enumerator` is private API used by the underlying job class, as you've discovered.

Here's an example of a custom task: https://github.com/Shopify/maintenance_tasks/blob/main/test/dummy/app/tasks/maintenance/custom_enumerating_task.rb

Would you be up for opening a PR to fix the documentation?

**Comment by yjukaku** [comment]
👍 Sure, I'll do that now.
