### ISSUE TITLE
CsvCollection doesn't work with the classic autoloader

### ISSUE THREAD

**Issue by etiennebarrie** [Shopify/maintenance_tasks#347]
Repro step:

```sh-session
$ CLASSIC_AUTOLOADER=1 rails s
```

**Comment by rafaelfranca** [comment]
Should we care? The classic autoloader is deprecated and being removed in 2 months.

**Comment by rafaelfranca** [comment]
It depends in the fix of course, but path and the constant name if matching so I don't see why this would be working in the classic autoloader.

**Comment by etiennebarrie** [comment]
It's our code made to make the classic autoloader work which isn't right, it loads the app code before the framework code.
