### ISSUE TITLE
Remove dependency on Pagy

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [Shopify/maintenance_tasks#362]
[Pagy](https://github.com/ddnexus/pagy) is a nice, simple pagination gem that we turned to for paginating previous runs. However, it uses offset, which is prohibited in Shopify Core:
![Screen Shot 2021-03-03 at 2 48 46 PM](https://user-images.githubusercontent.com/22918438/109877595-35aa3e00-7c41-11eb-9d6b-603d9175d0ee.png)

and just generally won't scale well. Plus, most apps don't really need paginated runs since they'll just run a Task once. It might be worthwhile to investigate removing Pagy and implementing some sort of value-based pagination, or even dropping pagination and allowing users to load more data on their page with a button click at the bottom of their page.

**Comment by simonlevasseur** [comment]
I saw your linked PR and it seems you have a pretty good handle on things but wanted to link a similar issue we had in Partners. We analyzed the performance implications of value-based pagination vs offset-based pagination. Not only is the performance better but it's also more reliable as documents change.

See https://github.com/Shopify/partners/pull/23097

**Comment by adrianna-chang-shopify** [comment]
That's an awesome writeup, thanks for sharing @simonlevasseur ! ❤️  The more I read up on the two, the more apparent it became that we should make the switch, but it's really neat to see the performance implications in an actual production application.
