### ISSUE TITLE
Framework should work nicely with structured logger

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [Shopify/maintenance_tasks#365]
The [canonical logger](https://github.com/Shopify/shopify-cloud/blob/main/guides/logging.md) project is underway to provide structured logging in jobs.

Right now the logger doesn't work well with the Maintenance Tasks gem because the logs get appended to after each iteration and are only written when the job is stopped.

We want to keep the gem as Shopify-agnostic as possible, but we should keep an eye out on making sure the gem integrates with the structured logger for Shopify apps. Supposedly the canonical logger will be compatible with iterative jobs once structured logging is in Rails 7.0.

**Comment by adrianna-chang-shopify** [comment]
Looks like the team who worked on structures logging is not intending to build compatibility with job iteration after all. In this case, we should probably allow apps to opt-out of logging (or disable the Job Iteration logs altogether).

**Comment by thomasbarton** [comment]
Here is a ticket to track discussion -> https://github.com/Shopify/observability/issues/587

**Comment by bdewater** [comment]
FWIW https://github.com/Shopify/job-iteration/pull/338 will help, `JobIteration::LogSubscriber.detach_from(:iteration)` and `attach_to` your own log subscriber.
