### ISSUE TITLE
Sometimes tasks randomly fail with status validation error (Shipify)

### ISSUE THREAD

**Issue by kostyl** [Shopify/maintenance_tasks#378]
Example: https://shipify.shopifycloud.com/internal/maintenance_tasks/tasks/Maintenance::BackfillLabelsMissingTrackerIdsTask

cc @raggedkarma

**Comment by adrianna-chang-shopify** [comment]
Hey folks, this was fixed [by this PR](https://github.com/Shopify/maintenance_tasks/pull/345) and released in [v1.1.1](MaintenanceTasks v1.1.1), so updating should do the trick.
