### ISSUE TITLE
CSV task fails if uuid is used for active_storage_attachments.record_id

### ISSUE THREAD

**Issue by shouichi** [Shopify/maintenance_tasks#462]
Background

We use uuid for primary keys, thus `active_storage_attachments.record_id` is uuid. On the other hand, `maintenance_tasks_runs.id` is `bigint`. Therefore, when a CSV task tries to upload a CSV as an `ActiveStorage::Attachment`, the attachment fails to reference the CSV task's run record (`MaintenanceTasks::Run`) because of the type inconsistency.

Possible solutions

- Document that the generated migration file must be manually edited when uuid is used.
- Respect `g.orm :active_record, primary_key_type: :uuid` when generating the migration file.

Thanks in advance.

**Comment by shouichi** [comment]
Unfortunately simply changing `maintenance_tasks_runs.id` to uuid did not work because of the following code.

https://github.com/Shopify/maintenance_tasks/blob/e64cdf0c265f67dd3a487c5fb0db8dc9df5464d4/app/models/maintenance_tasks/task_data.rb#L44

**Comment by shouichi** [comment]
The project only uses sqlite for testing. It seems that the first step is using both sqlite and postgres for testing. Is this the right direction @etiennebarrie ?

**Comment by etiennebarrie** [comment]
Yes, if it's necessary. I wonder if we could just test UUIDs with sqlite?

**Comment by shouichi** [comment]
Mmm, maybe we could use blob as a primary key and store uuid. I'll take a look.

**Comment by shouichi** [comment]
Changed primary keys to uuid, ran tests, and found that the current code depends on monotonically increasing ID more than I thought. For example, `Run.last` or `Run.where("id < ?", @cursor)`. It would be better to change incrementally. The first step should be to stop depending on monotonically increasing IDs. Does this make sense?

**Comment by etiennebarrie** [comment]
I'm not sure how which approach we should take:
* make all code dependencies on monotonically-increasing IDs abstract so we can change the behavior when using UUIDs, but keep the behavior as it is f

**Comment by shouichi** [comment]
Thanks for the advice.

> If we can avoid a migration, then the first solution is great: we don't need two code paths for UUIDs. But if we need more work for existing users, I think the second solution would be preferable.

Honestly, I'm not sure if we can avoid migration or not.

> In these situations, I tend to do a spike so that I can see all the moving parts, even if I end up shipping change incrementally. I would favor having a branch where we can see everything we will need, even things aren't perfect or tests fail.

OK. I'm going to open a PR that simply changes pk type to uuid so we can discuss it more in detail. Then, I'm also going to open several PRs against the first PR branch. So that PRs stay small (though the last merge might end up large).

**Comment by dhnaranjo** [comment]
I found myself in this situation and decided to hack it out with some monkeypatching. I might look to submitting this as an actual PR  but for now I thought I'd just offer this to anyone else who has a similar short-sighted need.

I'm using Zeitwerk overrides as described here: https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html#decorating-classes-and-modules-from-engines

It uses ActiveRecordExtended for a window function because I was already using it, I'm sure we wouldn't want to pull this dependency into the gem but it could certainly be written without it.

```
# app/overrides/maintenance_tasks/run_override.rb

module MaintenanceTasks
  class Run < ApplicationRecord
    scope :last_completed_per_task, -> do
      window_cte = define_window(:ended_at_window)
        .partition_by(:task_name, order_by: {ended_at: :desc})
        .select(:id)
        .select_window(:row_number, over: :ended_at_window, as: :ended_position)

      completed
        .with(run_ended_positions: window_cte)
        .joins("JOIN run_ended_positions ON run_ended_positions.id = maintenance_tasks_runs.id")
        .where(run_ended_positions: {ended_position: 1})
    end
  end
end
```

```
# app/overrides/maintenance_tasks/task_data_index_override.rb

module MaintenanceTasks
  class TaskDataIndex
    class << self
      def available_tasks
        tasks = []

        task_names = Task.available_tasks.map(&:name)

        active_runs = Run.with_attached_csv.active.where(task_name: task_names)
        active_runs.each do |run|
          tasks << TaskDataIndex.new(run.task_name, run)
          task_names.delete(run.task_name)
        end

        last_runs = Run.with_attached_csv.last_completed_per_task.where(task_name: task_names)
        task_names.map do |task_name|
          last_run = last_runs.find { |run| run.task_name == task_name }
          tasks << TaskDataIndex.new(task_name, last_run)
        end

        # We add an additional sorting key (status) to avoid possible
        # inconsistencies across database adapters when a Task has
        # multiple active Runs.
        tasks.sort_by! { |task| [task.name, task.status] }
      end
    end
  end
end
```

```
# db/migrate/###_maintenance_tasks_runs_uuid_pkey.rb

class MaintenanceTasksRunsUuidPkey < ActiveRecord::Migration[7.0]
  def change
    add_column :maintenance_tasks_runs, :uuid, :uuid, default: "gen_random_uuid()", null: false
    change_table :maintenance_tasks_runs do |t|
      t.remove :id
      t.rename :uuid, :id
    end
    execute "ALTER TABLE maintenance_tasks_runs ADD PRIMARY KEY (id);"
  end
end
```

And now I can run CSV tasks. No tests, no promises, works for me.

**Comment by harm-matthias-harms** [comment]
@dhnaranjo Approach seems to work for us, but I don't know if it comes with unknown implications. (This is also holding me back from doing a PR)

**Comment by gregpardo** [comment]
This is a similar patch based on the version posted above but without the additional gem dependency. Still need to convert columns to UUID as above. I put this into an an initializer. Use at own risk

```ruby
Rails.application.config.to_prepare do
  MaintenanceTasks::Run.class_eval do
    scope :last_completed_per_task, -> {
      subquery = completed
                   .select(:id, Arel.sql("ROW_NUMBER() OVER (PARTITION BY task_name ORDER BY ended_at DESC) AS ended_position"))
                   .to_sql

      # Join this subquery as a derived table and filter to where ended_position = 1
      joins("INNER JOIN (#{subquery}) run_ended_positions ON run_ended_positions.id = maintenance_tasks_runs.id")
        .where("run_ended_positions.ended_position = 1")
    }
  end

  module MaintenanceTasks
    class TaskDataIndex
      class << self
        def available_tasks
          tasks = []

          task_names = Task.available_tasks.map(&:name)

          active_runs = Run.with_attached_csv.active.where(task_name: task_names)
          active_runs.each do |run|
            tasks << TaskDataIndex.new(run.task_name, run)
            task_names.delete(run.task_name)
          end

          last_runs = Run.with_attached_csv.last_completed_per_task.where(task_name: task_names)
          task_names.map do |task_name|
            last_run = last_runs.find { |run| run.task_name == task_name }
            tasks << TaskDataIndex.new(task_name, last_run)
          end

          # We add additional sorting key (status) to avoid possible
          # inconsistencies across database adapters when a Task has
          # multiple active Runs.
          tasks.sort_by! { |task| [task.name, task.status] }
        end
      end
    end
  end
end
```

**Comment by etiennebarrie** [comment]
We could add the `last_completed_per_task` scope, and make it dependent on the database/generators configuration.
I think we both need to check for `Rails.configuration.generators.options[:active_record].fetch(:primary_key_type, :primary_key) == :uuid`, and for `MaintenanceTasks::ApplicationRecord.connection_pool.db_config.adapter == : postgresql`- for the partition SQL dialect?
Would you like to contribute these changes?
