### ISSUE TITLE
Support attribute descriptions

### ISSUE THREAD

**Issue by gmac** [Shopify/maintenance_tasks#477]
When defining attributes, it would be extremely useful if supporting descriptions could also be specified. These supporting descriptions would be included in the web UI with each attribute input field, and could provide some instructions about what the attribute does and what it's possible values and uses are.

**Comment by adrianna-chang-shopify** [comment]
Hey @gmac ! The task source code is included in the UI - why not just add a comment above each attribute with a description / acceptable values, etc?
