### ISSUE TITLE
Support for collection-less one-off tasks

### ISSUE THREAD

**Issue by promulo** [Shopify/maintenance_tasks#568]
Currently, tasks are supposed to execute over elements of a given collection. However, there is the use case of a task that doesn't really need a collection and just executes something once (e.g. triggering an async job, interacting with an external API). This behavior can be achieved in the gem by, for example, creating a collection with a single element which is just a workaround.

I am creating this issue in order to kick-off a discussion about supporting tasks that don't rely on collections "natively". Happy to collaborate on this if needed.

**Comment by adrianna-chang-shopify** [comment]
Makes sense to me to support this. We've seen a number of folks in Core ask for this, and our suggestion to iterate over a collection of `[1]` is not the nicest API.

This should be fairly easy to build using Job Iteration's `build_once_enumerator`:
https://github.com/Shopify/job-iteration/blob/b459d6f696c04e9e93a40fba97ee5e12f3b2f579/lib/job-iteration/enumerator_builder.rb#L39-L41

The tricker piece is going to be the API from the task side. We could use a class-level method like we did for CSV tasks:

```ruby
  class ProcessOnceTask < MaintenanceTasks::Task
    no_collection   # could also be process_once, etc...

    def process
      # Do something
    end
  end
```

Or we could just allow users to omit a collection and interpret that as a task that only calls process once:
 ```ruby
  class ProcessOnceTask < MaintenanceTasks::Task
    def process
      # Do something
    end
  end
```
(I think here we risk being unclear if a user accidentally omits a collection).

cc @Shopify/rails

**Comment by nvasilevski** [comment]
Makes sense for me as well 👍 

Personally I would prefer having a macro similar to the `csv_collection` one we have for csv tasks
