### ISSUE TITLE
Use Turbo stream instead of a meta tag to refresh page

### ISSUE THREAD

**Issue by elfassy** [Shopify/maintenance_tasks#569]
The [current solution](https://github.com/Shopify/maintenance_tasks/blob/main/app/views/layouts/maintenance_tasks/application.html.erb#L35) for refreshing the page was good as a MVP, but it comes with some problems:
- hard to search / scroll as the page always moves back to the top (#510)
- hard to copy paste text or links

Suggestion:
Use rails' turbo https://turbo.hotwired.dev/handbook/streams

**Comment by TopRoupi** [comment]
my suggestion would be just to add a refresh button in the nav bar and stop with the auto refresh every 3 seconds.
