### ISSUE TITLE
File not found error in production

### ISSUE THREAD

**Issue by coder2000** [Shopify/maintenance_tasks#592]
I have a nagging feeling I am missing something. After writing a task that takes a CSV and updates a model I have hit a dead end. The task works perfectly when I run it locally in testing but after uploading to my staging server every time I try I just get `ActiveStorage::FileNotFoundError`. I can find the file when I SSH into the server and the UI lets me download it but I can't get the task to run. What am I missing?

**Comment by adrianna-chang-shopify** [comment]
Hey @coder2000 ! Do you have a stack trace I can look at?

Can you also share the Ruby / Rails versions you're using, and details on your Active Storage setup?

Thanks!

**Comment by coder2000** [comment]
I am a dummy. Sidekiq runs on a different server from where ActiveStorage saves the file, so the path doesn't exist for the task.
