### ISSUE TITLE
Potentially unexpected memoization behavior

### ISSUE THREAD

**Issue by benjyblack** [Shopify/maintenance_tasks#614]
When dealing with a CSV collection, there is the potential for unexpected behavior when using memoization:

Given CSV:

```csv
user_id
1
2
```

and contrived example task:

```ruby
class UserMigratorTask < MaintenanceTasks::Task
  csv_collection
  
  def process(row)
    @user ||= User.find(row["user_id"])

    # ...

    @user.migrate!
  end
end
```

I (maybe naively) expected this task to iterate twice, once on user 1 and once on user 2. Unfortunately it actually iterates twice on user 1.

This is because the same task object instance is reused between both calls to `#process`, and therefore the instance variable is memoized between them.

I wonder if we should add a disclaimer in the README about this? I can see it catching other developers off guard as well.

**Comment by nvasilevski** [comment]
I may be having just different perspective on this, but for me, `collection` and `process` method being instance methods sends a strong signal that they may be used in scope of the same instance of the maintenance task and we should account for that

**Comment by benjyblack** [comment]
Thanks for the quick responses.

The code that actually bit me looked more like this:

```ruby
class UserMigratorTask < MaintenanceTasks::Task
  csv_collection
  
  def process(row)
    @row = row

    if !user.can_migrate?
      log_message("Unable to migrate")

      return
    end

    user.migrate!

    log_message("Finished successfully")
  end

  private
  
  def user
    @user ||= User.find(@row["user_id"])
  end

  def log_message(message)
    log_append(user: user, message: message)
  end
end
```

i.e. I was using a memoized instance method so that I could access the `user` object easily within other methods without having to explicitly pass it.

I've seen this pattern used when writing (for instance) Sidekiq jobs. Instead of having everything inside of the `#perform` method, some variables are extracted into memoized private methods for easy reference. The difference there is that `#perform` only operates on one set of parameters, so we don't run into this problem.

Having written this out, I feel less strongly about it. The code pattern is pretty nuanced and maybe is bad form. I would be curious if anyone else runs into this though.

**Comment by nvasilevski** [comment]
Perhaps the existence of this class method may lead to this confusion and perhaps we could remove it as at first glance we don't seem to use it anywhere except tests

https://github.com/Shopify/maintenance_tasks/blob/e1765da66ff0c870891c8608a7260f8a8292ac0e/app/models/maintenance_tasks/task.rb#L85-L92

And even it tests I feel like we may benefit from allocating an instance of the task so explicitly set our expectations, like we do here:

https://github.com/Shopify/maintenance_tasks/blob/e1765da66ff0c870891c8608a7260f8a8292ac0e/test/models/maintenance_tasks/csv_collection_builder_test.rb#L8

**Comment by adrianna-chang-shopify** [comment]
A simple way to do this would be to keep the ivar but drop the memoization:
```ruby
class UserMigratorTask < MaintenanceTasks::Task
  csv_collection
  
  def process(row)
   @user = User.find(@row["user_id"])

   if !@user.can_migrate?
      log_message("Unable to migrate")

      return
    end

    @user.migrate!

    log_message("Finished successfully")
  end

  private
  
  def log_message(message)
    log_append(user: @user, message: message)
  end
end
```
This ensures the ivar gets reassigned every time `#process` is called.

@nvasilevski it might be a bit tricky to drop that method because the task test templates use `TaskClass.process`, so it would technically be a breaking change and users would have to migrate all of their test cases over to instantiate the class.

**Comment by adrianna-chang-shopify** [comment]
I'm going to close this since I think it's been addressed 😄  Thanks for the issue, Ben!

**Comment by etiennebarrie** [comment]
I opened #632 to document this.
