### ISSUE TITLE
[Low Priority] Dark mode

### ISSUE THREAD

**Issue by larouxn** [Shopify/maintenance_tasks#768]
Low priority. Would be nice to have a dark mode. Personally interested in trying to implement it.

**Comment by george-ma** [comment]
Until this is added, a work around: [kepler approved dark reader extension](https://kepler.shopify.io/services/dark-reader)

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/20158582/226436638-2b759885-1e2b-4562-a9a3-2f4cd2ffd827.png">
