### ISSUE TITLE
Set max_job_runtime in TaskJob instead of hijacking JobIteration's global config

### ISSUE THREAD

**Issue by adamzapasnik** [Shopify/maintenance_tasks#781]
It's possible to set `max_job_runtime` per job https://github.com/Shopify/job-iteration/commit/64655bd83afb42de632fb78368609e3dbd67e028 so why not do that?

Right now the default is set:
```ruby
config.after_initialize do
  JobIteration.max_job_runtime ||= 5.minutes
end
```

which is unexpected when you use JobIteration for non maintenance_tasks' jobs. Imo, maintenance_tasks shouldn't "pollute" a global config unnecessarily? Is it even possible to tune it if it's being set in the `after_initialize` callback (probably it's)?

**Comment by etiennebarrie** [comment]
Also that commit hasn't been released yet, so we still can't use it. And there's an issue with the implementation, it breaks `JobIteration.max_job_runtime` as far as I can see.
