### ISSUE TITLE
Changing batch size on causes the job to skip records

### ISSUE THREAD

**Issue by vahe** [Shopify/maintenance_tasks#796]
While running CSV task with a batch, we updated the code to increase the batch size.

Initially we expected this to "just work". After further analysis we concluded this will cause unexpected behaviour for a currently running task. This was confirmed with a deploy of the change to increase the batch size. 

Once the code was deployed and the task was picked up again, maintenance task thought it was completed (since progress/cursor was calculated and persisted based on the previous batch size before the task was interrupted by deploy)

Steps to reproduce:
1. Start a task with large CSV and batch size of 10
2. Update batch size to 20 and deploy
3. Task progress jumps 2x (task might be marked as completed if progress was > 50% for example)

This UX is risky - users might not realize the progress was not calculated correctly and can lead to unprocessed records.

Would be really nice to have support for this!

**Comment by etiennebarrie** [comment]
We simply use job-iteration CSV batch enumerator. [It does use the batch index as the cursor (the call to `with_index` after `each_slice`)](https://github.com/Shopify/job-iteration/blob/a428f69fdaf210ad4d5225621eec6afebfed96e6/lib/job-iteration/csv_enumerator.rb#L41-L47), which explains why changing the batch size would skip records.

```
> 100 rows, batch size: 10
cursor: nil: rows:  0- 9, next cursor: 0
cursor:   0, rows: 10-19, next cursor: 1
> change batch size to 20
cursor:   1, rows: 40-59, next cursor: 2 # missing rows 20-39
```

It could and maybe should be changed to use the row index as the cursor, allowing to change the batch size while still returning the correct records on the next iteration.

```
> 100 rows, batch size: 10
cursor: nil: rows:  0- 9, next cursor: 9
cursor:  9, rows: 10-19, next cursor: 19
> change batch size to 20
cursor:  19, rows: 20-39, next cursor: 39
```

While we could paper over it by changing the cursor information on this side, the fix should ultimately be in job-iteration.
