### ISSUE TITLE
Persist user email

### ISSUE THREAD

**Issue by elfassy** [Shopify/maintenance_tasks#844]
It would be great to see who initiated the maintenance task. This could be done if we let the app configure the method to call to get the user's email
```ruby
MaintenanceTask.config do |config|
  config.user_email_method = :current_user_email
end
```

Then when we create the Runner, we can pass along the email to be saved in the DB. This is something that's required on banking. Happy to open the PR

**Comment by henryaj** [comment]
This would be awesome!

**Comment by gmcgibbon** [comment]
Yes, user-identifying metadata on the run makes sense to me. PRs are welcome!

**Comment by gmcgibbon** [comment]
Aha, thank you @etiennebarrie. Sorry for the confusion.
