### ISSUE TITLE
How do we set `limit`?

### ISSUE THREAD

**Issue by bray** [Shopify/maintenance_tasks#890]
When `collection` returns an `ActiveRecord::Relation`, how do we set `limit` for each "batch"?  `job-iteration`'s [Best Practices](https://github.com/Shopify/job-iteration/blob/1ebc6974cceddd7e526630e85875059cf6c9da0f/guides/best-practices.md#batch-iteration) says it defaults to 100.  100 is too small for expensive queries and/or large datasets.

It looks like that's passed in [here](https://github.com/Shopify/job-iteration/blob/1ebc6974cceddd7e526630e85875059cf6c9da0f/lib/job-iteration/active_record_enumerator.rb#L10-L12).

But for `maintenance_tasks`, in the `collection` method, we're not explicitly building an enumerator. So how can we pass in or set the `@batch_size`?  I've tried some guesses like `@batch_size`, `@of`, `def batch_size`, `def of` inside the `MaintenanceTasks::Task`.

I also tried returning a few different classes in the collection method, but none have worked:

`#find_each(batch_size: 2000)` gets us what we want, but this returns an Enumerator and `#collection` can't be an Enumerator (it gives the error "#collection must be either an Active Record Relation, ActiveRecord::Batches::BatchEnumerator, Array, or CSV.").

`#in_batches(batch_size: 2000)` works (it returns an `ActiveRecord::Batches::BatchEnumerator`), but this is only if you want to [process a batch](https://github.com/Shopify/maintenance_tasks/tree/main#processing-batch-collections) in process, rather than individual items.

`#in_batches(batch_size: 2000).each_record` also returns an Enumerator.

**Comment by nvasilevski** [comment]
I'd say this is purely a missing API as there is no reason not to allow tasks to redefine the batch size that is being used under the hood. The batch size will need to be passed to the `active_record_on_records` enumerator using the `batch_size:` option
https://github.com/Shopify/maintenance_tasks/blob/e1765da66ff0c870891c8608a7260f8a8292ac0e/app/jobs/concerns/maintenance_tasks/task_job_concern.rb#L42

So I'll try to put it on our roadmap or PRs are always welcomed! Unless someone else from maintainers remembers/has concerns on why this feature should not exist

The only requirement for this feature is that the tasks shouldn't be forced to always specify the batch size and it still should default to `100` (or to `nil` which means we'll use the default from `job-iteration`)

**Comment by bray** [comment]
Ok, thanks - good to know I wasn't missing something. I'll try to get up a PR!

An example would be: say you have to process 50 million records. If you fetch 100 per query, that's 500,000 queries. As opposed to 50,000 or 10,000 if you fetch 1k or 5k per query. If the query takes negligibly longer for the larger batch size, it's probably better to do a larger batch size to greatly reduce the number of queries in a potentially small time window.

That's a good point re: `max_job_runtime`. To be honest, I've set that to infinity to disable the periodic interruptions. I understand the tasks should be *interruptable*, but don't really see the benefit of forcing interrupts every 5 minutes. The reasoning given [here](https://github.com/Shopify/job-iteration/blob/1ebc6974cceddd7e526630e85875059cf6c9da0f/guides/best-practices.md#max-job-runtime) is to preserver worker capacity. But we'll be running these tasks in their own Sidekiq queue with dedicated workers, so that's not a concern for us.

So in our case, a big batch size is irrelevant. But I understand we have to keep that in mind for changes to the gem.

**Comment by nvasilevski** [comment]
I'm a little worried that any name with `_limit_` in it may mislead users into thinking that this is the max number of records the task is supposed to iterate over. Personally I would prefer having `_batch_` in the name

But the prototype looks clean!

**Comment by bray** [comment]
I agree with Nikita. Looks good, but `s/limit/batch_size/g` :)
