### ISSUE TITLE
Web UI and Rails API mode

### ISSUE THREAD

**Issue by afuno** [Shopify/maintenance_tasks#926]
Hello.

Can you please tell me how I can currently use the Web UI section in a Rails application that runs in API mode?

I get an error:

```
undefined method `flash' for #<ActionDispatch::Request GET "http://localhost:3000/maintenance_tasks" for ::1>
```

Is it possible, by defining the operating mode of a Rails application, to remove the definition/use of these methods?

**Comment by afuno** [comment]
Solution:

```ruby
class Maintenance::Tasks::ApplicationController < ActionController::Base
  include ActionDispatch::Flash::RequestMethods
end
```

```ruby
MaintenanceTasks.parent_controller = "Maintenance::Tasks::ApplicationController"
```

**Comment by etiennebarrie** [comment]
If this is all it takes, we could support it out of the box.

**Comment by xandrck** [comment]
Hey, @afuno, thanks for the tip.
Could you tell me how you solved the CSRF problem, did you add views for pause/cancel actions? 
I have a pure rails API project, and I have an error `can't verify CSRF token authenticity` when I run it locally by pressing any of the action buttons (Pause/Cancel)

**Comment by xandrck** [comment]
Thanks for the solution @afuno !
Could you tell me how you resolved `CSRF token authenticity` error for all `POST` actions?

p.s. `skip_before_action :verify_authenticity_token` didn't help me.
