### ISSUE TITLE
CSV Task Failure: ActiveRecord::NotNullViolation Error on UUID record_id

### ISSUE THREAD

**Issue by longstackup** [Shopify/maintenance_tasks#946]
I'm using Rails 7.1.2. I followed the instruction about [Creating a CSV Task](https://github.com/Shopify/maintenance_tasks?tab=readme-ov-file#creating-a-csv-task). But when choose CSV file and run task, this error happen: `ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "record_id" of relation "active_storage_attachments" violates not-null constraint`

![screenshot_2024-01-05_at_17 06 10](https://github.com/Shopify/maintenance_tasks/assets/121844686/ef2746ce-2456-4029-8a58-93e399c2c6dc)

I also config Active Storage follow [setup intructions](https://edgeguides.rubyonrails.org/active_storage_overview.html#setup). My code work well with upload file in other places. And `record_id` column in `active_storage_attachments` table using uuid

```
  create_table "active_storage_attachments", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.uuid "record_id", null: false
    t.uuid "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end
 ```
 
 How can I resolve this ? Thanks in advance.

**Comment by nvasilevski** [comment]
Must be the same as https://github.com/Shopify/maintenance_tasks/issues/462

**Comment by gmcgibbon** [comment]
Indeed it seems to be a duplicate. Let's move any discussions to the other issue.
