### ISSUE TITLE
please add a CHANGELOG.md file

### ISSUE THREAD

**Issue by tilo** [Shopify/maintenance_tasks#965]
there is no CHANGELOG.md file in this project

this makes it hard to understand what changed, and if there are breaking changes

**Comment by nvasilevski** [comment]
While it doesn't mean we shouldn't have a changelog I wanted to mention that we are trying our best providing the most accurate changes description, including breaking changes in the release notes, for example: https://github.com/Shopify/maintenance_tasks/releases/tag/v2.0.0

Having said that, I don't think it will be a huge burden to maintain a CHANGELOG. @Shopify/rails should we start maintaining one? Perhaps starting from the next release

**Comment by lastgabs** [comment]
@tilo thanks for the request. 

As per @etiennebarrie 's reply, we're not planning on adding a changelog because it adds more friction than solves problems, so I'll close the issue for now.

**Comment by tilo** [comment]
@etiennebarrie yes, I understand that you don't want to spend extra time on this!

oh - you already have the basic file!! 😮 it is just not in a standard location where people (or RubyGems.org) would expect it :) 

This should make your existing changelog more discoverable: https://github.com/Shopify/maintenance_tasks/pull/966
