### ISSUE TITLE
Change `PUT` methods to `POST` methods for better compat with API mode apps

### ISSUE THREAD

**Issue by ChanChar** [Shopify/maintenance_tasks#992]
Similar to https://github.com/Shopify/maintenance_tasks/issues/926, Rails API mode doesn't include the middleware that converts POST to PUT calls leading to `Routing Error`s.

Possible solutions:

1. Create a custom controller and set the parent to that.
2. Generator checks for all required middleware and adds them to the application. 

References https://github.com/Shopify/sidekick-server/issues/728

**Comment by etiennebarrie** [comment]
Would you be interested in contributing these changes?

**Comment by etiennebarrie** [comment]
We should stop using PUTs and switch to POSTs.
